{
  logsForTarget: [
    {
      MessageTemplate: Receive message {IncomingMessageType} {IncomingMessageId}.,
      Level: Information,
      Properties: {
        IncomingMessage: {
          TypeTag: StartHandlerThatLogs
        },
        OriginatingHostId: Guid_1,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatLogs,
        OriginatingMachine: TheMachineName,
        ReplyToAddress: SerilogTestsStartHandlerThatLogs,
        TimeSent: DateTime_1,
        IncomingMessageId: Guid_2,
        IncomingMessageType: StartHandlerThatLogs,
        IncomingMessageTypeFull: StartHandlerThatLogs, Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=ce8ec7717ba6fbb6,
        CorrelationId: Guid_2,
        ConversationId: Guid_3,
        SourceContext: StartHandlerThatLogs,
        ProcessingEndpoint: SerilogTestsStartHandlerThatLogs
      }
    },
    {
      MessageTemplate: Sent message {OutgoingMessageType} {OutgoingMessageId}.,
      Level: Information,
      Properties: {
        OutgoingMessage: {
          TypeTag: StartHandlerThatLogs
        },
        UnicastRoutes: {
          Elements: [
            SerilogTestsStartHandlerThatLogs
          ]
        },
        OriginatingHostId: Guid_1,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatLogs,
        OriginatingMachine: TheMachineName,
        ReplyToAddress: SerilogTestsStartHandlerThatLogs,
        OutgoingMessageId: Guid_2,
        OutgoingMessageType: StartHandlerThatLogs,
        OutgoingMessageTypeFull: StartHandlerThatLogs,
        CorrelationId: Guid_2,
        ConversationId: Guid_3,
        SourceContext: StartHandlerThatLogs,
        ProcessingEndpoint: SerilogTestsStartHandlerThatLogs
      }
    }
  ],
  logsWithExceptions: [
    {
      MessageTemplate: The message,
      Level: Error,
      Properties: {
        SourceContext: TheHandlerThatThrows,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "HResult": -2146233088,
            "Message": Exception of type 'System.Exception' was thrown.,
            "Source": null
          }
        }
      }
    }
  ]
}